### ISSUE TITLE
No normalization before training?

### ISSUE THREAD

**Issue by qimingyudaowenti** [zjfheart/Geometry-aware-Instance-reweighted-Adversarial-Training#2]
Thanks for sharing your code. I notice that there is no normalize operation ((img-mean)/std) in data pre-processing when train GAIRAT. Is it just for simplicity?

**Comment by ZFancy** [comment]
> Thanks for sharing your code. I notice that there is no normalize operation ((img-mean)/std) in data pre-processing when train GAIRAT. Is it just for simplicity?

Hi Geyao,

Thanks for your attention to our code!

First of all, there is indeed no normalize operation ((img-mean)/std) in data preprocessing of our code, which keeps the same as the previous adversarial training methods, such as TRADES [1] and MART [2]. (You can refer to https://github.com/yaodongyu/TRADES or https://github.com/YisenWang/MART)

Second, since the adversarial training needs to generate the adversarial examples for the input data, you may need additional operations or different \epsilon if you add the normalize operation in data preprocessing which changes the input value. If you want to add this operation, you can refer to https://github.com/locuslab/robust_overfitting.

Third, according to some previous experiments, we have not found the influence of this operation on the effect of the adversarial training. Considering the fair comparison with other methods, we did not add this operation.

Best wishes,
Jianing

[1] Zhang, Hongyang, et al. "Theoretically principled trade-off between robustness and accuracy." International Conference on Machine Learning. PMLR, 2019.
[2] Wang, Yisen, et al. "Improving adversarial robustness requires revisiting misclassified examples." International Conference on Learning Representations. 2019.

**Comment by qimingyudaowenti** [comment]
Thank you for the kind and detailed reply! I still have a question that, is the Madry-AT baseline result conducted with the normalization?

**Comment by zjfheart** [comment]
> Thank you for the kind and detailed reply! I still have a question that, is the Madry-AT baseline result conducted with the normalization?

Yes! Basically, all the adv training methods such as TRADES, MART and FAT follow Madry-AT's normalization style, i.e., without ((img-mean)/std), for fair comparisons.

**Comment by qimingyudaowenti** [comment]
Got it! :rose:
